steps:
  # Steps to pull a docker image for pgadmin, push it to container registry, and deploy it to Cloud Run.
  - name: "gcr.io/cloud-builders/docker"
    args: ['pull', 'dpage/pgadmin4']

  - name: "gcr.io/cloud-builders/docker"
    args: ['tag', 'dpage/pgadmin4', 'gcr.io/assignment6-project-441620/pgadmin']

  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/assignment6-project-441620/pgadmin']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pg-admin'
      - '--image'
      - 'gcr.io/assignment6-project-441620/pgadmin'
      - '--region'
      - 'us-central1'
      - '--add-cloudsql-instances'
      - 'assignment6-project-441620:us-central1:mypostgres'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PGADMIN_DEFAULT_EMAIL=user@gmail.com'
      - '--set-env-vars'
      - 'PGADMIN_DEFAULT_PASSWORD=SuperSecret'

  # Steps to build a docker image for go-microservice, push it to container registry, and deploy it to Cloud Run.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'gcr.io/assignment6-project-441620/go-microservice'
      - '-f'
      - 'src/data_service/Dockerfile'  # Path to your Dockerfile (within the src/data_service directory)
      - '.'  # Build context should be the root directory to include everything in src/data_service

  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/assignment6-project-441620/go-microservice']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'go-microservice'
      - '--image'
      - 'gcr.io/assignment6-project-441620/go-microservice'
      - '--region'
      - 'us-central1'
      - '--add-cloudsql-instances'
      - 'assignment6-project-441620:us-central1:mypostgres'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      # - '--set-env-vars'
      # - 'GO_MICROSERVICE_URL=https://go-microservice-550412521327.us-central1.run.app'

  # Steps to build a docker image for flask app, push it to container registry, and deploy it to Cloud Run.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '-f'
      - 'src/flask_app/Dockerfile'  # Path to your Flask Dockerfile
      - '.'  # Build context should be the root directory to include everything in src/flask_app

  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/assignment6-project-441620/flask-app']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5000'
      - '--allow-unauthenticated'
      # - '--set-env-vars'
      # - 'GO_MICROSERVICE_URL=https://go-microservice-550412521327.us-central1.run.app'  # Passing URL to Flask app

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/assignment6-project-441620/go-microservice'
  - 'gcr.io/assignment6-project-441620/pgadmin'
  - 'gcr.io/assignment6-project-441620/flask-app'
