steps:
  # Step 1: Build the Flask app Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '-f'
      - 'src/flask-app/Dockerfile'  # Path to your Flask Dockerfile
      - 'src/flask-app'  # Build context should be the root directory (or src/flask_app if Dockerfile is inside that folder)

  # Step 2: Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/assignment6-project-441620/flask-app']

  # Step 3: Deploy the Flask app to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5000'
      - '--allow-unauthenticated'
      #- '--set-env-vars'
     # - 'GO_MICROSERVICE_URL=https://your-go-service-url'  # Pass URL of the Go microservice to Flask

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/assignment6-project-441620/flask-app'
