steps:
  # Step to build a docker image for flask app, push it to container registry, and deploy it to Cloud Run.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '-f'
      - 'src/flask-app/Dockerfile'  # Path to your Flask Dockerfile
      - './src/flask-app'  # Build context to include everything in the src/flask-app directory

  - name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/assignment6-project-441620/flask-app']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/assignment6-project-441620/flask-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5000'
      - '--allow-unauthenticated'
      # Uncomment and adjust if you need environment variables:
      # - '--set-env-vars'
      # - 'GO_MICROSERVICE_URL=https://go-microservice-550412521327.us-central1.run.app' 

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/assignment6-project-441620/flask-app'
